# docker-compose.yml

version: '3.8'

services:
  neo4j:
    image: neo4j:5.8.0
    container_name: neo4j
    ports:
      - "7474:7474"    # Neo4j Browser
      - "7687:7687"    # Bolt protocol
    environment:
      NEO4J_AUTH: neo4j/your_password  # Change to a secure password
    volumes:
      - neo4j_data:/data

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=your_password  # Must match NEO4J_AUTH
      - JWT_SECRET=your_jwt_secret
      - PORT=5000
    depends_on:
      - neo4j
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/usr/src/app

volumes:
  neo4j_data:
